apiVersion: v1
kind: ServiceAccount
metadata:
  name: global-pull-secret-sync-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "global-pull-secret-synch.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: global-pull-secret-sync-role
  labels:
    {{- include "global-pull-secret-synch.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["pull-secret"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: global-pull-secret-sync-rb
  labels:
    {{- include "global-pull-secret-synch.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: global-pull-secret-sa
    namespace: openshift-config
  - kind: ServiceAccount
    name: global-pull-secret-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: global-pull-secret-role
  apiGroup: rbac.authorization.k8s.io
