apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "global-pull-secret-synch.labels" . | nindent 4 }}
data:
  global-pull-secret-sync.sh: |
    #!/bin/bash

    ls-la /host

