apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "global-pull-secret-synch.labels" . | nindent 4 }}
data:
  global-pull-secret-sync.sh: |
    #!/bin/bash

    while true
    do
      ls -la /host
      cat /host/.dockerconfigjson
      sleep 5m
    done



